### ISSUE TITLE
Write-only interface (clarification requested)

### ISSUE THREAD

**Issue by etherbrat** [tesla-local-control/tesla-local-control-addon#105]
The Addon returns "Presence" but appears to be write-only in all other cases. I assume "Presence" comes from the BLE node, not the Tesla itself (i.e. the Tesla is completely write-only). To save me from trawling through code which I would barely understand, could I ask whether the interface is write-only because retrieving data from the Tesla is not allowed/supported by Tesla, or whether it is because no contributor has got around to it yet. I have read the note stating that a change to a setting by a command from elsewhere will not result in the change being notified to this interface, but could the relevant quantities be polled for the current value? For the purposes of energy management, and some other use cases, it would be nice to be able to retrieve values from the Tesla, e.g. state of charge, charger plugged in, etc. Is this possible, or not. If it is possible, I might try to contribute. I assume that code to retrieve a value could easily be copied and modified to retrieve a different value. Thanks in advance.

**Comment by iainbullock** [comment]
It is not currently possible to retrieve values from the Tesla Bluetooth API. If you want values / sensors you will have to use the Fleet API in addition to this. Presence detection doesn't use the Tesla Bluetooth API

**Comment by etherbrat** [comment]
Thank you for your prompt response. That being the case (and by the way I got the BLE interface working quite easily), it is not clear to me what the most common / easiest hosting option is for the http proxy for the Fleet API. Do people host it at home using Dynamic DNS (I really don’t want the Internet inside my house), or do they pay for a third party cloud node? A bit off topic for this project, I guess, but I’s appreciate any advice. Thanks again.

**Comment by iainbullock** [comment]
I can't speak for most people, but there is no need to pay for it. These projects provide the capability:

https://github.com/alandtse/tesla

then one of the following HTTP-PROXIES:

https://github.com/llamafilm/tesla-http-proxy-addon (if you want to HA add-on), or

https://github.com/iainbullock/tesla-http-proxy-docker (if you want a docker version).

The proxies are not easy to setup, you need your own domain name and webserver (e.g. nginx) on your network which can serve https with full certification accessible from the internet. It's worth persevering as you get lots of sensors and many commands (which are duplicates of those provided by this project). Note the Tesla Fleet API has usage limits per day so its best to use bluetooth for sending commands, as you rapidly get limited if you send lots of command (maybe >50 per day)

**Comment by etherbrat** [comment]
Yah, I know about those (thanks). The issue (for me) is summed up in your words “ … you need your own domain name and web server … accessible from the internet”. This implies some kind of overhead - either home-hosting or cloud-hosting of the web server. Yuk to both - I tip my hat to those who are enthusiastic enough, but not for me. I’ll do the best I can with the BLE interface, for which I am duly grateful.

**Comment by iainbullock** [comment]
Fair enough. If Tesla add more features e.g. ability to read data we will implement.
