### ISSUE TITLE
Error when trying toi install Tesla local control addon on HAOS

### ISSUE THREAD

**Issue by HiFuGa** [tesla-local-control/tesla-local-control-addon#107]
Hello,

I have HAOS, with following versions :

Core : 2024.9.0
Supervisor : 2024.08.0
Operating System :13.1
Interface utilisateur : 20240904.0

I am able to add the addon on Home Assistant, but when I click "Install", I get this fault and it is not installed :

![Tesla-local](https://github.com/user-attachments/assets/4065b065-857e-4d2f-a3b2-002d306f9cb5)

I have this message in the logs :

![Tesla-local-2](https://github.com/user-attachments/assets/3f6454bf-4c72-40d3-af48-82a58040d8ac)

This is the procedure I followed to install it, let me know if I am doing something wrong, or if there is a real bug to fix :

I clicked this button :

![Tesla-local-3](https://github.com/user-attachments/assets/6bcc4df9-7017-4509-98dd-90c03e074c44)

Then I clicked "Add" :

![Tesla-local-4](https://github.com/user-attachments/assets/30be8b01-a776-44fd-80ce-2cbd81d32795)

I clicked on the addon after refreshing the page :

![Tesla-local-5](https://github.com/user-attachments/assets/621578ac-0fe5-45c1-b512-3707f27f9ce1)

Then I clicked "Install" :

![Tesla-local-6](https://github.com/user-attachments/assets/cc17e731-9288-4191-b9ad-45d2215ca1ca)

Thank you !

**Comment by penapena** [comment]
Did you find out how to get it to work? I have the same issue

**Comment by iainbullock** [comment]
I can't comment from experience, I'm using the docker version with no issue. @raphmur @baylanger any comments regarding the error message above? Thanks

**Comment by raphmur** [comment]
Hello
Yes, I have seen this issue on HACF forum already. This is probably due to a go compile error with HAOS.
HAOS uses go 1.21, tesla app now requires 1.23.
We will update in the upcoming days.

Will post here

**Comment by penapena** [comment]
Works now with the new version
