### ISSUE TITLE
Entities disappeared but integration seems to be running

### ISSUE THREAD

**Issue by vdiogo** [tesla-local-control/tesla-local-control-addon#121]
I have been using this add-on since some months without issues, but since today I have noted that all entities are now unavailable:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/68b21f55-4ee8-404a-9a75-f73eba81b4ce" />

Upon checking the add-on logs, I noted the add-on is able to connect to the car and sending commands (the commands are managed by node-red), so I wonder what the issue could be. Attaching the logs. 
[da013fb0_tesla_local_commands_2024-12-12T14-28-48.178Z.log](https://github.com/user-attachments/files/18113057/da013fb0_tesla_local_commands_2024-12-12T14-28-48.178Z.log)

Many thanks for helping me out here

**Comment by vdiogo** [comment]
Interestingly, all entities are back today:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/6c91289e-4f39-42e9-ac64-175c1510861f" />

**Comment by iainbullock** [comment]
Not sure what happened, I hope that's the end of your problem
