### ISSUE TITLE
Issue with unique IDs

### ISSUE THREAD

**Issue by epenet** [tesla-local-control/tesla-local-control-addon#19]
I think it doesn't really make sense to use `"identifiers": ["tesla_ble_mqtt"],` and `"unique_id": "tesla_ble_presence"`

Both should really include the VIN of the car to make it trully unique.

Maybe something like `"identifiers": ["tesla_ble_mqtt_" + VIN]` and `"unique_id": "tesla_ble_mqtt_" + VIN + "_presence"`

**Comment by iainbullock** [comment]
Agreed. We'll need to do something like you suggest to support multi-car scenarios

**Comment by iainbullock** [comment]
@raphmur I'll fix this one. There is a user on my repo asking for a multicar solution

**Comment by raphmur** [comment]
ok thanks @iainbullock. Can you ping back on this issue when introduced? I'll copy the changes

**Comment by raphmur** [comment]
We discussed yesterday and more or less agreed on this naming:
tesla_ble/[entity type]/[vin]/msg

identifiers and id will be a combination of this

**Comment by raphmur** [comment]
Hi, should have been solved in latest release.
It currently only handles 3 vins, until we merge the latest PR (already drafted by @baylanger)
Please re-open if this is still an issue
