### ISSUE TITLE
Invalid Configuration request on scan_bluetooth

### ISSUE THREAD

**Issue by epenet** [tesla-local-control/tesla-local-control-addon#21]
When I press the scan_bluetooth button in HA, I get this error message
```
Received MQTT message: tesla_ble/config scan_bluetooth
Configuration scan_bluetooth requested
Invalid Configuration request. Topic: tesla_ble/config Message: scan_bluetooth
```

**Comment by iainbullock** [comment]
This one is work in progress. On my repo I intend to calculate the SxxxxxxxxxxxxxxxxC version from the VIN then can for this so the user can select the corresponding 74:B8:39:XX:YY:ZZ version

I haven't found a way of calculating the 74:B8:39:XX:YY:ZZ  version from the VIN

**Comment by iainbullock** [comment]
@raphmur I'll fix this one

**Comment by baylanger** [comment]
@iainbullock since I had to split PR #16 , while in there I made changes to BLE_MAC and adding function to generate the value. See PR #26

**Comment by iainbullock** [comment]
Excellent work thanks. I could calculated the advertisement string but not the MAC. I will look at your code to see how you did it!

**Comment by baylanger** [comment]
I took the code from [here](https://github.com/iainbullock/tesla_ble_mqtt_docker/issues/10#issuecomment-2171927357) - did I miss something? 🤔

**Comment by iainbullock** [comment]
I haven't had time to check the code. The advertisement string will work but I think the MAC is preferable as it appears on the scan more frequently

**Comment by baylanger** [comment]
> @baylanger please do not call it MAC. Your code is computing the `S...C` advertisement code. It is not computing the MAC.
> 
It is BLE_MAC just because I reused the var name :)  

> If the advertisement code is sufficient for detection, then great 👍 but it is still not a MAC.
>
Agreed on the MAC.

I was reading on [this](https://devzone.nordicsemi.com/guides/short-range-guides/b/bluetooth-low-energy/posts/ble-advertising-a-beginners-tutorial) topic.

- The 'MAC' in BLE world is called "Bluetooth Device Address"
- I'm unclear if the "S...C" is refereed as "Bluetooth Device Name" or something else.... so I'm unclear how to rename the variable ... could always use "BLE_SC" :D

**Comment by baylanger** [comment]
> I haven't had time to check the code. The advertisement string will work but I think the MAC is preferable as it appears on the scan more frequently
>
When I use nRF Connect I never see a BLE Device Address. I look at the app's settings, I don't see what I could change. I do see other devices' address but definitely not from the vehicle.

**Comment by epenet** [comment]
I'll get a screenshot from android ble scanner tomorrow

**Comment by iainbullock** [comment]
@epenet 

Please can you run this. You should get your MAC. I was going to include this in the repo but can't test it as I'm on holiday and car is not at home. Use the VIN for your case of course

VIN_HASH=`echo -n "LRW3Fxxxxxxxxxxx03" | sha1sum`
 BLE_ADVERT=S${VIN_HASH:0:16}C
 
 bluetoothctl --timeout 10 scan on | grep $BLE_ADVERT

**Comment by epenet** [comment]
I am with the car... 20km from HA. So won't be before tomorrow. 
I'm also not sure how to run those commands. Is it on the HA root ssh? Or do I need to somehow jump onto the addon terminal?

**Comment by iainbullock** [comment]
Ok no problem. HA root ssh should be ok.

**Comment by baylanger** [comment]
> @epenet
> 
> Please can you run this. You should get your MAC. I was going to include this in the repo but can't test it as I'm on holiday and car is not at home. Use the VIN for your case of course
> 
> VIN_HASH=`echo -n "LRW3Fxxxxxxxxxxx03" | sha1sum` BLE_ADVERT=S${VIN_HASH:0:16}C
> 
> bluetoothctl --timeout 10 scan on | grep $BLE_ADVERT
>

It returns the S....C name not the device address:
```
$ VIN_HASH=$(echo -n "5YJ3E1EB6JFxxxxxx" | sha1sum | sed -e 's/ .*//g')
$ echo $VIN_HASH
bd04bf13a78c1f0e6a17f8xxxxxxxxxb4ad2
$ BLE_ADVERT=S${VIN_HASH:0:16}C; echo $BLE_ADVERT
Sbd04bxxxxxxx0eC
```

**Comment by baylanger** [comment]
I'll update the PR to use that to generate the S..C name instead of the Python code.

**Comment by iainbullock** [comment]
Can you run 

bluetoothctl --timeout 10 scan on | grep $BLE_ADVERT

Does that not report anything?

Thanks

**Comment by epenet** [comment]
I managed to run it from my phone via ssh addon

It doesn't report anything for either advert or mac

```
$ bluetoothctl --timeout 10 scan on | grep $BLE_ADVERT
$ bluetoothctl --timeout 10 scan on | grep $BLE_MAC
```

**Comment by baylanger** [comment]
Oh it was previously working aka "reporting the presence" because of this bug now fixed in PR #22  - lol

**Comment by baylanger** [comment]
Is it possible the Device Address is only reported when the car is awake but the "S.....C" name reported all the time?   I didn't wake up my car earlier when I went to try to see an address.

**Comment by iainbullock** [comment]
Maybe or I'm thinking I might have had another device associated with the car that I thought was the car. I can't test my situation until I get home

**Comment by epenet** [comment]
> I'll get a screenshot from android ble scanner tomorrow

![image](https://github.com/raphmur/tesla-local-control-addon/assets/6771947/036996f2-39de-47d5-94c9-3e28531b1e58)

**Comment by baylanger** [comment]
I went back to the vehicle - not sure on Android but `nRF Connect` allows filtering by signal strength... setting a minimum value, the S..C name shows up but no address at all.

Dig around and found out that bluetoothctl might not look by default for LE devices.

```
menu scan
transport le
back
scan on
```

bluetoothctl [man page](https://www.mankier.com/1/bluetoothctl#Automation)

I'm unclear if a scan off is required to change the transport. If so....
```
# scan off
[bluetooth]# Failed to stop discovery: org.bluez.Error.Failed
```

Perhaps we need to configure bluez for LE transport?!

**Comment by baylanger** [comment]
Anyone has `hcitool lescan` configured on one of their box?  Apparently that one can scan for BLE devices.... it might output the device's address + the name (in our case the S...C name) but I'm not sure.

I tried adding more tools but it fails.
```
RUN apk add --no-cache bluez-tools
RUN apk add --no-cache rfkill
RUN apk add --no-cache rfcomm
```
Not pro enough to figure out if there's an easy way to add those... unless we git checkout/compile & install?

**Comment by baylanger** [comment]
<img width="340" alt="2024-06-18_16-11-41" src="https://github.com/raphmur/tesla-local-control-addon/assets/5240348/254f132e-fb31-44cd-a223-c442696e2e4b">

Ref: https://www.pcsuggest.com/linux-bluetooth-setup-hcitool-bluez/

**Comment by iainbullock** [comment]
I'm doing mine in a docker environment so it might produce different result to the add on situation

**Comment by raphmur** [comment]
Hi all
Thanks for your involvement! I will try and catchup tomorrow on the PRs

**Comment by baylanger** [comment]
> Hi all Thanks for your involvement! I will try and catchup tomorrow on the PRs
>
Little note my PRs - To reduce as much as possible any conflict, each PR was merged with the previous one. They were all tested - Except the standalone one but I think it should be just fine.

There's an issue for bluetoothctl to scan LE devices... by default LE isn't enable and bluez might be prevented us to tell bluetoothctl to use "LE transport". See here above ^^

Can't join Discord channel... says invalid or expired :/

**Comment by baylanger** [comment]
From [here](https://teslamotorsclub.com/tmc/threads/tesla-bluetooth-low-energy-ble-api-documentation.245114/) I ended up on this [site](https://teslabtapi.lexnastin.com/docs/intro) explaining a bit in details Tesla BLE.

Something interesting to know:
> The vehicle has a BLE connection limit of 3 devices (from what I've seen on my M3LR). If you try to connect another device, it will not be able to, and will just give an error on the device trying to connect.

What does this mean? My phone, my wife's phone and ... the bluetooth dongle and that's it?

**Comment by raphmur** [comment]
Should be solved here https://github.com/tesla-local-control/tesla_ble_mqtt_core/pull/12 @baylanger ?

**Comment by raphmur** [comment]
Processed in [v0.1.0 release](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0)

As of today we are explicitly requiring the MAC of the car to scan for presence.
But you can use the `Scan Bluetooth` to search for visible devices

For the next release we will be working on a reliable solution that is all VIN based (ie. no need to provide MAC)
