### ISSUE TITLE
Run BLE presence only if enable & generate BLE_MAC fom VIN

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla-local-control-addon#26]
Currently if BLE_MAC is defined, BLE presence will run every ~3m

We can do better:
- Autogen BLE_MAC from VIN - thus removing BLE_MAC config option
- Add config option to enable or not presence detection

**Comment by raphmur** [comment]
PR #32 ready, it should solve this

**Comment by raphmur** [comment]
Solved in [v0.1.0 release](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0) obviously
