### ISSUE TITLE
No retry logic => Unable to connect (Lookup error) etc

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla-local-control-addon#29]
Upgrded the network switch and noticed the container went dead.

mosquitto_sub failed to connect to MQTT:
> Unable to connect (Lookup error.

Should we make this better? Implement t there be some logic to retry X times when there's a DNS or network issue?

**Comment by raphmur** [comment]
Indeed... Restarting the addon solved the issue?
Btw there is a "watchdog" option, which so far did not have any effect for me, meaning not restarting after crash

**Comment by baylanger** [comment]
Yes restarting did it. I don't have WatchDog enable but can take a look why it fails to restart at all on failure if WD is enable.

**Comment by iainbullock** [comment]
Is there an equivilant of the docker-compose.yml restart: unless-stopped option? Would this achieve what you are suggesting? Also have set +e during the shell scripts except where we are specifically looking for the exit status value should catch other failures and cause a restart of the container

**Comment by raphmur** [comment]
I think we are good for now by processing the output of tesla-control in [v0.1.0 release](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0)
Improvement forseen in v1.0.0
