### ISSUE TITLE
Standalone version documentation issues

### ISSUE THREAD

**Issue by epenet** [tesla-local-control/tesla-local-control-addon#38]
I'm trying to switch from https://github.com/iainbullock/tesla_ble_mqtt_docker to the standalone version here, and the docs are not working for me

https://github.com/tesla-local-control/tesla-local-control-addon/blob/06e3c6ad52e06355f396cb78b70606e5de49dd31/tesla_ble_mqtt/DOCS.md?plain=1#L27-L33

**Comment by raphmur** [comment]
I'll have a look

**Comment by epenet** [comment]
Side note: I found the BUILD_FROM from the HA docs.
```
- armhf: homeassistant/armhf-base:latest
- aarch64: homeassistant/aarch64-base:latest
- amd64: homeassistant/amd64-base:latest
- i386: homeassistant/i386-base:latest
```

**Comment by epenet** [comment]
Small progress => the root cause of the `s6-envdir` error is the shell: `#!/command/with-contenv bashio`
It seems that bashio is not available in the base images mentioned above

**Comment by baylanger** [comment]
@epenet you can track the progress to fix the standalone mode in fix-standalone - I have changes that might get merged into this branch soon.

**Comment by epenet** [comment]
> @epenet you can track the progress to fix the standalone mode in fix-standalone - I have changes that might get merged into this branch soon.

Which base image do you use in your testing?
Or are you coding blind for the standalone?
For now I've reverted to the iainbullock image.

**Comment by raphmur** [comment]
Please see https://github.com/tesla-local-control/tesla_ble_mqtt_docker, standalone has been solved. Please open issue there if this is still not working.
