### ISSUE TITLE
Could the version be added to the MQTT device information?

### ISSUE THREAD

**Issue by epenet** [tesla-local-control/tesla-local-control-addon#41]
Could the version be added to the MQTT device information?

I think it should be straightforward adding `sw_version` to 
https://github.com/tesla-local-control/tesla-local-control-addon/blob/a44f6b561decc03bdfc269ba5cbf2640b16ca752/tesla_ble_mqtt/rootfs/app/discovery.sh#L8-L13

**Comment by iainbullock** [comment]
Yes I can add a sw_version field to the MQTT "device" map section. 

Any ideas how best to get the value for this? e.g. 

- There is a "version" field in config.yaml, is there a way to extract this in the code? 
- Better still use a GitHub variable which contains a value representing the release, but then how do you reference this in the various files that want to use it

I suppose I want to avoid having various files containing static data which we have to remember to update everytime we do a new release

**Comment by iainbullock** [comment]
> Yes I can add a sw_version field to the MQTT "device" map section.
> 
> Any ideas how best to get the value for this? e.g.
> 
> * There is a "version" field in config.yaml, is there a way to extract this in the code?
> * Better still use a GitHub variable which contains a value representing the release, but then how do you reference this in the various files that want to use it
> 
> I suppose I want to avoid having various files containing static data which we have to remember to update everytime we do a new release

@epenet any idea or help on this would be appreciated. I can look at this myself when I get time.....

**Comment by raphmur** [comment]
Yes, if you know something easy in Github...
To make it clear, we will now have:
- tesla-local-control-addon --> Version is in `config.yaml` + `Changelog.md`. So far it is manually updated, with missed shots sometime
- tesla_ble_mqtt_docker (standalone version) --> Version is in releases. Maybe to be added in docker-compose?
- tesla_ble_mqtt_core (core .sh files) --> No need for version there yet if it can be pushed as a variable from the other 2 repos.

What would make more sense is to have the version in the _core repo and push it to -addon & _docker? git automation?

**Comment by baylanger** [comment]
>     * tesla-local-control-addon --> Version is in `config.yaml` + `Changelog.md`. So far it is manually updated, with missed shots sometime
> 
>     * tesla_ble_mqtt_docker (standalone version) --> Version is in releases. Maybe to be added in docker-compose?
> 
Shouldn't docker-compose just have `latest`? Out of ~12-15 containers that I run, unless I want to run beta images, they're all set to `latest`.

> What would make more sense is to have the version in the _core repo and push it to -addon & _docker? git automation?
>
I had not paid attention to the new _core repo.... it might be better to do the opposition. addon/docker fetches from the _core - could be a hook with a wget/curl to a raw `version` file.

**Comment by epenet** [comment]
Note: I think the version here should be the one from the core repo - and it can be different from the one in the addon yaml

**Comment by baylanger** [comment]
@epenet Thanx for your input. We were aiming to addOnVersion-coreVersion or vice-versa, ex: 0.1.0-0.2.0 but it's possible we'd do ex. 0.1.0 and in the ChangeLog mention the core version.

We haven't get to the point it's automated. Once we get there and figure out how we can do it, some decisions will be taken.

In the Changelog we'd mention which one is which one. We haven't

**Comment by raphmur** [comment]
See https://github.com/tesla-local-control/tesla_ble_mqtt_core/blob/main/discovery.sh it has been added. Should be working now with v0.0.11

**Comment by raphmur** [comment]
Version now added in [v0.1.0 release](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0)

![image](https://github.com/user-attachments/assets/50884802-211d-4620-b88a-4f7a8e9805a5)
