### ISSUE TITLE
[standalone] Reduce mem usage, use shell sh (busybox) instead of bash

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla-local-control-addon#45]
See #43 for tests results.
See #44 the actual changes

**Comment by raphmur** [comment]
Please merge #43

**Comment by baylanger** [comment]
My error - this is actually for #45 not #43

**Comment by raphmur** [comment]
@baylanger for HA addon, they almost all run with bashio... I think we can keep it.
I will propose a PR

**Comment by raphmur** [comment]
Closing this one. Sticking to bashio for HA addon
