### ISSUE TITLE
Move from _core run.sh code specific to add-on

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla-local-control-addon#59]
Take "add-on related" code from run.sh and paste in `libproduct.sh` inside a function named `LoadConfig()` or something similar.

Create the main function named `productInit()` that calls `LoadConfig()`.

In _core there's code being added to source`../libproduct.sh` (if available).

**Comment by raphmur** [comment]
Fixed in [v0.1.0 release](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0) thanks @baylanger
